name: Doxygen GitHub Pages Deploy Action WebRTC C SDK

on:
  push:
    branches:
      - master
      - develop

jobs:
  generate-and-deploy-doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      
      - name: Install requirements
        run: sudo apt-get install doxygen graphviz -y
        shell: bash

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile
        shell: bash
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@830e6a4f7c81743c52f3fed0ac67428feff9620a # v4.2.5
        with:
          folder: doc/html
          branch: gh-pages
      